<style type="text/css">
.node {cursor: pointer;}
</style>
<div style="position: relative">
    <div id="d3body"></div>
</div>
<script type="text/javascript" src="/static/js/d3.v3.min.js"></script>
<script type="text/javascript" src="/static/js/saveSvgAsPng.js"></script>
<script type="text/javascript">
var relationTree={daochu:function(){saveSvgAsPng($("#d3body>svg")[0],"relation.png");},show:function(){var that=this;$.post('<?=$_request_url?>',{},function(data){that.paint(data);},'json');},paint:function(treeData){var totalNodes=0;var maxLabelLength=0;var panSpeed=200;var i=0;var duration=750;var root;var viewerWidth=$(document).width()-220;var viewerHeight=$(document).height()-80;var tree=d3.layout.tree().size([viewerHeight,viewerWidth]);var diagonal=d3.svg.diagonal().projection(function(d){return[d.y,d.x];});function visit(parent,visitFn,childrenFn){if(!parent)return;visitFn(parent);var children=childrenFn(parent);if(children){var count=children.length;for(var i=0;i<count;i++){visit(children[i],visitFn,childrenFn);}}}
visit(treeData,function(d){totalNodes++;maxLabelLength=Math.max(d.name.length,maxLabelLength);},function(d){return d.children&&d.children.length>0?d.children:null;});function sortTree(){tree.sort(function(a,b){return b.name.toLowerCase()<a.name.toLowerCase()?1:-1;});}
function pan(domNode,direction){var speed=panSpeed;if(panTimer){clearTimeout(panTimer);translateCoords=d3.transform(svgGroup.attr("transform"));if(direction=='left'||direction=='right'){translateX=direction=='left'?translateCoords.translate[0]+speed:translateCoords.translate[0]-speed;translateY=translateCoords.translate[1];}else if(direction=='up'||direction=='down'){translateX=translateCoords.translate[0];translateY=direction=='up'?translateCoords.translate[1]+speed:translateCoords.translate[1]-speed;}
scaleX=translateCoords.scale[0];scaleY=translateCoords.scale[1];scale=zoomListener.scale();svgGroup.transition().attr("transform","translate("+translateX+","+translateY+")scale("+scale+")");d3.select(domNode).select('g.node').attr("transform","translate("+translateX+","+translateY+")");zoomListener.scale(zoomListener.scale());zoomListener.translate([translateX,translateY]);panTimer=setTimeout(function(){pan(domNode,speed,direction);},50);}}
function zoom(){svgGroup.attr("transform","translate("+d3.event.translate+")scale("+d3.event.scale+")");}
var zoomListener=d3.behavior.zoom().scaleExtent([0.1,3]).on("zoom",zoom);var baseSvg=d3.select("#d3body").html('').append("svg").attr("width",viewerWidth).attr("height",viewerHeight).style("background-color","#fff").call(zoomListener);function collapse(d){if(d.children){d._children=d.children;d._children.forEach(collapse);d.children=null;}}
function expand(d){if(d._children){d.children=d._children;d.children.forEach(expand);d._children=null;}}
function toggleChildren(d){if(d.children){d._children=d.children;d.children=null;}else if(d._children){d.children=d._children;d._children=null;}
return d;}
function click(d){if(d3.event.defaultPrevented)return;d=toggleChildren(d);update(d);}
function update(source){var levelWidth=[1];var childCount=function(level,n){if(n.children&&n.children.length>0){if(levelWidth.length<=level+1)levelWidth.push(0);levelWidth[level+1]+=n.children.length;n.children.forEach(function(d){childCount(level+1,d);});}};childCount(0,root);var newHeight=d3.max(levelWidth)*50;if(newHeight>viewerHeight){$("#d3body>svg").attr('height',newHeight+50);}
tree=tree.size([newHeight,viewerWidth]);var nodes=tree.nodes(root).reverse(),links=tree.links(nodes);nodes.forEach(function(d){d.y=d.depth*150;});var node=svgGroup.selectAll("g.node").data(nodes,function(d){return d.id||(d.id=++i);});var nodeEnter=node.enter().append("g").attr("class","node").attr("transform",function(d){return"translate("+source.y0+","+source.x0+")";}).on('click',click);nodeEnter.append("circle").attr("r",0).attr("style",function(d){return'stroke:steelblue;stroke-width:1.5px;'+(d._children?'fill:lightsteelblue':'fill:#fff');});nodeEnter.append("text").attr("x",function(d){return d.children||d._children?-10:10;}).attr("dy",".35em").attr("text-anchor",function(d){return d.children||d._children?"end":"start";}).attr('style',function(d){return'font-size:14px;fill-opacity:1;'+(d.is_manager?'font-weight:bold;fill:red;':'');}).text(function(d){return d.name;});node.select("circle").attr("r",4.5).attr("style",function(d){return'stroke:steelblue;stroke-width:1.5px;'+(d._children?'fill:lightsteelblue':'fill:#fff');});var nodeUpdate=node.transition().duration(duration).attr("transform",function(d){return"translate("+d.y+","+d.x+")";});nodeUpdate.select("text").style("fill-opacity",1);var nodeExit=node.exit().transition().duration(duration).attr("transform",function(d){return"translate("+source.y+","+source.x+")";}).remove();nodeExit.select("circle").attr("r",0);nodeExit.select("text").style("fill-opacity",0);var link=svgGroup.selectAll("path.link").data(links,function(d){return d.target.id;});link.enter().insert("path","g").attr("class","link").attr("d",function(d){var o={x:source.x0,y:source.y0};return diagonal({source:o,target:o});}).attr('style',function(d){return'fill:none;stroke-width:0.5px;stroke:#333;'+(d.target.type=='industry'?'':'stroke-dasharray:5;');});link.transition().duration(duration).attr("d",diagonal);link.exit().transition().duration(duration).attr("d",function(d){var o={x:source.x,y:source.y};return diagonal({source:o,target:o});}).remove();nodes.forEach(function(d){d.x0=d.x;d.y0=d.y;});}
var svgGroup=baseSvg.append("g").attr("transform","translate(100,20)");root=treeData;root.x0=viewerHeight/2;root.y0=0;update(root);}};relationTree.show('recommend');</script>